commit

diff --git a/.github/workflows/drift-detection.yml b/.github/workflows/drift-detection.yml
--- a/.github/workflows/drift-detection.yml
+++ b/.github/workflows/drift-detection.yml
@@ -44,19 +44,29 @@ jobs:
       id: plan
       run: |
          terraform plan -no-color -detailed-exitcode
-         echo "exit_code=$?" >> $GITHUB_OUTPUT 
+         echo "exit_code=$?"
 
-    # Check for drift
-    - name: Check for Drift
-      run: |
-        if [ ${{ steps.plan.outputs.exit_code }} -eq 2 ]; then
-          echo "Drift detected!"
-        else
-          echo "No drift detected."
-        fi
+         if [ $exit_code -eq 0 ]; then
+           echo "No drift detected."
+         elif [ $exit_code -eq 1 ]; then
+           echo "Error in plan."
+           exit 1
+         elif [ $exit_code -eq 2 ]; then
+           echo "Drift detected."
+           terraform apply -auto-approve
+         fi
 
-    # Apply Terraform changes if drift is detected
-    - name: Apply if drift detected
-      if: steps.plan.outputs.exit_code == 2
-      run: terraform apply -auto-approve
+    # # Check for drift
+    # - name: Check for Drift
+    #   run: |
+    #     if [ ${{ steps.plan.outputs.exit_code }} -eq 2 ]; then
+    #       echo "Drift detected!"
+    #     else
+    #       echo "No drift detected."
+    #     fi
+
+    # # Apply Terraform changes if drift is detected
+    # - name: Apply if drift detected
+    #   if: steps.plan.outputs.exit_code == 2
+    #   run: terraform apply -auto-approve
 
