commit

diff --git a/.github/workflows/drift-detection.yml b/.github/workflows/drift-detection.yml
--- a/.github/workflows/drift-detection.yml
+++ b/.github/workflows/drift-detection.yml
@@ -41,4 +41,12 @@ jobs:
 
     # Generate Terraform plan for drift detection
     - name: Terraform Plan
-      run: terraform plan -no-color -detailed-exitcode -out=tfplan
+      run: |
+         terraform plan -no-color -detailed-exitcode -out=tfplan || export exit_code=$?
+         if [ "$exit_code" -eq 2 ]; then
+           echo "Drift detected!"
+           exit 1
+         elif [ "$exit_code" -ne 0 ]; then
+           echo "Error running terraform plan"
+           exit $exit_code
+         fi
